apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00547
  namespace: sno00547
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00547"
  labels:
    infraenvs.agent-install.openshift.io: "sno00547"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.60:9000/redfish/v1/Systems/9f73aded-a403-4133-9e70-2f897bc054b4'
    disableCertificateVerification: true
    credentialsName: sno00547-bmc-secret
  bootMACAddress: '52:54:00:76:2a:03'
  automatedCleaningMode: disabled
  online: true
