apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00521
  namespace: sno00521
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00521"
  labels:
    infraenvs.agent-install.openshift.io: "sno00521"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.56:9000/redfish/v1/Systems/d999fc85-1851-4ead-9945-9ab9be438b3f'
    disableCertificateVerification: true
    credentialsName: sno00521-bmc-secret
  bootMACAddress: '52:54:00:76:26:05'
  automatedCleaningMode: disabled
  online: true
