apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00560
  namespace: sno00560
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00560"
  labels:
    infraenvs.agent-install.openshift.io: "sno00560"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.62:9000/redfish/v1/Systems/10779c93-499a-4b6f-b7da-66f2e5e16d9c'
    disableCertificateVerification: true
    credentialsName: sno00560-bmc-secret
  bootMACAddress: '52:54:00:76:2c:02'
  automatedCleaningMode: disabled
  online: true
