apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00596
  namespace: sno00596
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00596"
  labels:
    infraenvs.agent-install.openshift.io: "sno00596"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.67:9000/redfish/v1/Systems/7c61055f-e760-47d6-abeb-6c6e0a40c364'
    disableCertificateVerification: true
    credentialsName: sno00596-bmc-secret
  bootMACAddress: '52:54:00:76:31:03'
  automatedCleaningMode: disabled
  online: true
