apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00530
  namespace: sno00530
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00530"
  labels:
    infraenvs.agent-install.openshift.io: "sno00530"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.57:9000/redfish/v1/Systems/d412671d-6dc2-4f6c-9593-b71caf291840'
    disableCertificateVerification: true
    credentialsName: sno00530-bmc-secret
  bootMACAddress: '52:54:00:76:27:07'
  automatedCleaningMode: disabled
  online: true
