apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00589
  namespace: sno00589
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00589"
  labels:
    infraenvs.agent-install.openshift.io: "sno00589"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.66:9000/redfish/v1/Systems/5a6cbb8f-63f1-413c-a8d6-1dcc5a7d5f54'
    disableCertificateVerification: true
    credentialsName: sno00589-bmc-secret
  bootMACAddress: '52:54:00:76:30:03'
  automatedCleaningMode: disabled
  online: true
