apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00534
  namespace: sno00534
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00534"
  labels:
    infraenvs.agent-install.openshift.io: "sno00534"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.58:9000/redfish/v1/Systems/768c9f40-6275-4a05-833b-b27fceb2d6f7'
    disableCertificateVerification: true
    credentialsName: sno00534-bmc-secret
  bootMACAddress: '52:54:00:76:28:04'
  automatedCleaningMode: disabled
  online: true
