apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00514
  namespace: sno00514
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00514"
  labels:
    infraenvs.agent-install.openshift.io: "sno00514"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.55:9000/redfish/v1/Systems/87568604-7e69-44d8-9a24-5379ccf8ff4c'
    disableCertificateVerification: true
    credentialsName: sno00514-bmc-secret
  bootMACAddress: '52:54:00:76:25:05'
  automatedCleaningMode: disabled
  online: true
