apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00558
  namespace: sno00558
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00558"
  labels:
    infraenvs.agent-install.openshift.io: "sno00558"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.61:9000/redfish/v1/Systems/154cdfe9-0341-4fb2-a2c9-b7146188bdf4'
    disableCertificateVerification: true
    credentialsName: sno00558-bmc-secret
  bootMACAddress: '52:54:00:76:2b:07'
  automatedCleaningMode: disabled
  online: true
