apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00510
  namespace: sno00510
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00510"
  labels:
    infraenvs.agent-install.openshift.io: "sno00510"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.55:9000/redfish/v1/Systems/430c296e-e9fe-487e-8d1d-ab782b6a9270'
    disableCertificateVerification: true
    credentialsName: sno00510-bmc-secret
  bootMACAddress: '52:54:00:76:25:01'
  automatedCleaningMode: disabled
  online: true
