apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00552
  namespace: sno00552
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00552"
  labels:
    infraenvs.agent-install.openshift.io: "sno00552"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.61:9000/redfish/v1/Systems/41abc675-973e-400f-b49b-a51ca9c3027b'
    disableCertificateVerification: true
    credentialsName: sno00552-bmc-secret
  bootMACAddress: '52:54:00:76:2b:01'
  automatedCleaningMode: disabled
  online: true
