apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00503
  namespace: sno00503
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00503"
  labels:
    infraenvs.agent-install.openshift.io: "sno00503"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.54:9000/redfish/v1/Systems/e31332c4-44c3-40ec-87bb-c555bbc286a2'
    disableCertificateVerification: true
    credentialsName: sno00503-bmc-secret
  bootMACAddress: '52:54:00:76:24:01'
  automatedCleaningMode: disabled
  online: true
