apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00524
  namespace: sno00524
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00524"
  labels:
    infraenvs.agent-install.openshift.io: "sno00524"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.57:9000/redfish/v1/Systems/541b122d-6027-4476-9dde-ccf080927029'
    disableCertificateVerification: true
    credentialsName: sno00524-bmc-secret
  bootMACAddress: '52:54:00:76:27:01'
  automatedCleaningMode: disabled
  online: true
