apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00509
  namespace: sno00509
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00509"
  labels:
    infraenvs.agent-install.openshift.io: "sno00509"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.54:9000/redfish/v1/Systems/405b2bef-251a-4da7-a79e-3ec989382c7f'
    disableCertificateVerification: true
    credentialsName: sno00509-bmc-secret
  bootMACAddress: '52:54:00:76:24:07'
  automatedCleaningMode: disabled
  online: true
