apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00523
  namespace: sno00523
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00523"
  labels:
    infraenvs.agent-install.openshift.io: "sno00523"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.56:9000/redfish/v1/Systems/10632b8c-e540-4440-b1fa-966b2c39b746'
    disableCertificateVerification: true
    credentialsName: sno00523-bmc-secret
  bootMACAddress: '52:54:00:76:26:07'
  automatedCleaningMode: disabled
  online: true
