apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00579
  namespace: sno00579
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00579"
  labels:
    infraenvs.agent-install.openshift.io: "sno00579"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.64:9000/redfish/v1/Systems/7e52429c-5eac-42a7-945a-30000459cc8c'
    disableCertificateVerification: true
    credentialsName: sno00579-bmc-secret
  bootMACAddress: '52:54:00:76:2e:07'
  automatedCleaningMode: disabled
  online: true
