apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00554
  namespace: sno00554
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00554"
  labels:
    infraenvs.agent-install.openshift.io: "sno00554"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.61:9000/redfish/v1/Systems/89f94aa4-2b13-4ca4-8f37-d3ae1b663db5'
    disableCertificateVerification: true
    credentialsName: sno00554-bmc-secret
  bootMACAddress: '52:54:00:76:2b:03'
  automatedCleaningMode: disabled
  online: true
