apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00526
  namespace: sno00526
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00526"
  labels:
    infraenvs.agent-install.openshift.io: "sno00526"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.57:9000/redfish/v1/Systems/72203761-3c0d-49c5-93b3-dfb6b0a33304'
    disableCertificateVerification: true
    credentialsName: sno00526-bmc-secret
  bootMACAddress: '52:54:00:76:27:03'
  automatedCleaningMode: disabled
  online: true
