apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00501
  namespace: sno00501
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00501"
  labels:
    infraenvs.agent-install.openshift.io: "sno00501"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.53:9000/redfish/v1/Systems/8bbf0d05-a9b3-4d13-b48c-4d103ee91534'
    disableCertificateVerification: true
    credentialsName: sno00501-bmc-secret
  bootMACAddress: '52:54:00:76:23:06'
  automatedCleaningMode: disabled
  online: true
