apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00570
  namespace: sno00570
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00570"
  labels:
    infraenvs.agent-install.openshift.io: "sno00570"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.63:9000/redfish/v1/Systems/4bcabc61-5bad-48bf-8573-097ba0382b53'
    disableCertificateVerification: true
    credentialsName: sno00570-bmc-secret
  bootMACAddress: '52:54:00:76:2d:05'
  automatedCleaningMode: disabled
  online: true
