apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00551
  namespace: sno00551
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00551"
  labels:
    infraenvs.agent-install.openshift.io: "sno00551"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.60:9000/redfish/v1/Systems/2994cbe4-1cce-4c29-9cd2-083453bd87f8'
    disableCertificateVerification: true
    credentialsName: sno00551-bmc-secret
  bootMACAddress: '52:54:00:76:2a:07'
  automatedCleaningMode: disabled
  online: true
