apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00597
  namespace: sno00597
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00597"
  labels:
    infraenvs.agent-install.openshift.io: "sno00597"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.67:9000/redfish/v1/Systems/13d2304c-9d78-4b5d-b8ba-24faf3465492'
    disableCertificateVerification: true
    credentialsName: sno00597-bmc-secret
  bootMACAddress: '52:54:00:76:31:04'
  automatedCleaningMode: disabled
  online: true
