apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00572
  namespace: sno00572
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00572"
  labels:
    infraenvs.agent-install.openshift.io: "sno00572"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.63:9000/redfish/v1/Systems/44e1d683-aaa9-45c7-a286-927b14ce69d0'
    disableCertificateVerification: true
    credentialsName: sno00572-bmc-secret
  bootMACAddress: '52:54:00:76:2d:07'
  automatedCleaningMode: disabled
  online: true
