apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00591
  namespace: sno00591
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00591"
  labels:
    infraenvs.agent-install.openshift.io: "sno00591"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.66:9000/redfish/v1/Systems/202ff465-c2f3-4284-845e-f58a6bc24f45'
    disableCertificateVerification: true
    credentialsName: sno00591-bmc-secret
  bootMACAddress: '52:54:00:76:30:05'
  automatedCleaningMode: disabled
  online: true
