apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00569
  namespace: sno00569
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00569"
  labels:
    infraenvs.agent-install.openshift.io: "sno00569"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.63:9000/redfish/v1/Systems/64cf6bf5-3e1f-4206-aa83-841678093740'
    disableCertificateVerification: true
    credentialsName: sno00569-bmc-secret
  bootMACAddress: '52:54:00:76:2d:04'
  automatedCleaningMode: disabled
  online: true
