apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00571
  namespace: sno00571
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00571"
  labels:
    infraenvs.agent-install.openshift.io: "sno00571"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.63:9000/redfish/v1/Systems/05838190-7052-4f6c-9f3b-267f2ea8a383'
    disableCertificateVerification: true
    credentialsName: sno00571-bmc-secret
  bootMACAddress: '52:54:00:76:2d:06'
  automatedCleaningMode: disabled
  online: true
