apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00542
  namespace: sno00542
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00542"
  labels:
    infraenvs.agent-install.openshift.io: "sno00542"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.59:9000/redfish/v1/Systems/fdfb8918-c0ee-42f4-959d-1fa703d4dc11'
    disableCertificateVerification: true
    credentialsName: sno00542-bmc-secret
  bootMACAddress: '52:54:00:76:29:05'
  automatedCleaningMode: disabled
  online: true
