apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00320
  namespace: sno00320
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00320"
  labels:
    infraenvs.agent-install.openshift.io: "sno00320"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/686e1ec2-f40a-45db-aad3-4e48ff367222'
    disableCertificateVerification: true
    credentialsName: sno00320-bmc-secret
  bootMACAddress: '52:54:00:76:12:0e'
  automatedCleaningMode: disabled
  online: true
