apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00331
  namespace: sno00331
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00331"
  labels:
    infraenvs.agent-install.openshift.io: "sno00331"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/f77a9e54-d9e5-491d-b515-65e6a0083af8'
    disableCertificateVerification: true
    credentialsName: sno00331-bmc-secret
  bootMACAddress: '52:54:00:76:13:08'
  automatedCleaningMode: disabled
  online: true
