apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00387
  namespace: sno00387
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00387"
  labels:
    infraenvs.agent-install.openshift.io: "sno00387"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/2dc2a334-0f0f-469f-92bf-5bcd2a6e010e'
    disableCertificateVerification: true
    credentialsName: sno00387-bmc-secret
  bootMACAddress: '52:54:00:76:16:0d'
  automatedCleaningMode: disabled
  online: true
