apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00361
  namespace: sno00361
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00361"
  labels:
    infraenvs.agent-install.openshift.io: "sno00361"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/ab00e07b-1815-48f6-880f-e7612983493d'
    disableCertificateVerification: true
    credentialsName: sno00361-bmc-secret
  bootMACAddress: '52:54:00:76:15:04'
  automatedCleaningMode: disabled
  online: true
