apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00307
  namespace: sno00307
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00307"
  labels:
    infraenvs.agent-install.openshift.io: "sno00307"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/34f36050-0baa-4c8f-9892-a7fd4e555fe8'
    disableCertificateVerification: true
    credentialsName: sno00307-bmc-secret
  bootMACAddress: '52:54:00:76:12:01'
  automatedCleaningMode: disabled
  online: true
