apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00382
  namespace: sno00382
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00382"
  labels:
    infraenvs.agent-install.openshift.io: "sno00382"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/b5b78ef3-df55-41c7-aebb-bd633799b911'
    disableCertificateVerification: true
    credentialsName: sno00382-bmc-secret
  bootMACAddress: '52:54:00:76:16:08'
  automatedCleaningMode: disabled
  online: true
