apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00372
  namespace: sno00372
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00372"
  labels:
    infraenvs.agent-install.openshift.io: "sno00372"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/50342597-1f7b-4c48-98ad-6dae873d0909'
    disableCertificateVerification: true
    credentialsName: sno00372-bmc-secret
  bootMACAddress: '52:54:00:76:15:0f'
  automatedCleaningMode: disabled
  online: true
