apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00318
  namespace: sno00318
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00318"
  labels:
    infraenvs.agent-install.openshift.io: "sno00318"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/7311df5b-1a1b-4f80-b551-0fa69ea95c12'
    disableCertificateVerification: true
    credentialsName: sno00318-bmc-secret
  bootMACAddress: '52:54:00:76:12:0c'
  automatedCleaningMode: disabled
  online: true
