apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00352
  namespace: sno00352
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00352"
  labels:
    infraenvs.agent-install.openshift.io: "sno00352"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/2acb3dfa-f00d-49bd-98f0-df4c6bcf9bd4'
    disableCertificateVerification: true
    credentialsName: sno00352-bmc-secret
  bootMACAddress: '52:54:00:76:14:0c'
  automatedCleaningMode: disabled
  online: true
