apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00314
  namespace: sno00314
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00314"
  labels:
    infraenvs.agent-install.openshift.io: "sno00314"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/bda4b9ea-1e12-41ec-a120-93d298469787'
    disableCertificateVerification: true
    credentialsName: sno00314-bmc-secret
  bootMACAddress: '52:54:00:76:12:08'
  automatedCleaningMode: disabled
  online: true
