apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00306
  namespace: sno00306
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00306"
  labels:
    infraenvs.agent-install.openshift.io: "sno00306"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/a61ef5fc-ce2c-4f17-9491-4d09e3f3e227'
    disableCertificateVerification: true
    credentialsName: sno00306-bmc-secret
  bootMACAddress: '52:54:00:76:11:11'
  automatedCleaningMode: disabled
  online: true
