apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00384
  namespace: sno00384
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00384"
  labels:
    infraenvs.agent-install.openshift.io: "sno00384"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/781f2b75-011c-4ac0-b96b-d30d242cf0e0'
    disableCertificateVerification: true
    credentialsName: sno00384-bmc-secret
  bootMACAddress: '52:54:00:76:16:0a'
  automatedCleaningMode: disabled
  online: true
