apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00315
  namespace: sno00315
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00315"
  labels:
    infraenvs.agent-install.openshift.io: "sno00315"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/ccec0915-76d3-4d2c-9ee2-0f37d0f346b8'
    disableCertificateVerification: true
    credentialsName: sno00315-bmc-secret
  bootMACAddress: '52:54:00:76:12:09'
  automatedCleaningMode: disabled
  online: true
