apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00321
  namespace: sno00321
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00321"
  labels:
    infraenvs.agent-install.openshift.io: "sno00321"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/38fb2a99-2815-4f3b-8b8a-5d6b7d98f53a'
    disableCertificateVerification: true
    credentialsName: sno00321-bmc-secret
  bootMACAddress: '52:54:00:76:12:0f'
  automatedCleaningMode: disabled
  online: true
