apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00341
  namespace: sno00341
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00341"
  labels:
    infraenvs.agent-install.openshift.io: "sno00341"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/04646778-324a-48ea-b4fe-cbf512cf88fe'
    disableCertificateVerification: true
    credentialsName: sno00341-bmc-secret
  bootMACAddress: '52:54:00:76:14:01'
  automatedCleaningMode: disabled
  online: true
