apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00350
  namespace: sno00350
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00350"
  labels:
    infraenvs.agent-install.openshift.io: "sno00350"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/27d55aa5-12fd-44e9-a518-39fe7fdcfccc'
    disableCertificateVerification: true
    credentialsName: sno00350-bmc-secret
  bootMACAddress: '52:54:00:76:14:0a'
  automatedCleaningMode: disabled
  online: true
