apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00357
  namespace: sno00357
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00357"
  labels:
    infraenvs.agent-install.openshift.io: "sno00357"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/38925caf-c159-4e2f-8f8a-4b3486c8ab0f'
    disableCertificateVerification: true
    credentialsName: sno00357-bmc-secret
  bootMACAddress: '52:54:00:76:14:11'
  automatedCleaningMode: disabled
  online: true
