apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00322
  namespace: sno00322
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00322"
  labels:
    infraenvs.agent-install.openshift.io: "sno00322"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/7fb6e7b3-8c83-4841-8418-84f8405f4dc4'
    disableCertificateVerification: true
    credentialsName: sno00322-bmc-secret
  bootMACAddress: '52:54:00:76:12:10'
  automatedCleaningMode: disabled
  online: true
