apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00367
  namespace: sno00367
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00367"
  labels:
    infraenvs.agent-install.openshift.io: "sno00367"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/a4aa118f-a1a4-46fa-9b94-3ddfb9006809'
    disableCertificateVerification: true
    credentialsName: sno00367-bmc-secret
  bootMACAddress: '52:54:00:76:15:0a'
  automatedCleaningMode: disabled
  online: true
