apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00346
  namespace: sno00346
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00346"
  labels:
    infraenvs.agent-install.openshift.io: "sno00346"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/213e41b9-9977-40a4-8c10-d72380a007c6'
    disableCertificateVerification: true
    credentialsName: sno00346-bmc-secret
  bootMACAddress: '52:54:00:76:14:06'
  automatedCleaningMode: disabled
  online: true
