apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00335
  namespace: sno00335
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00335"
  labels:
    infraenvs.agent-install.openshift.io: "sno00335"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/0ff73d97-e9a1-4cb3-ab4f-0f6b94eafdc9'
    disableCertificateVerification: true
    credentialsName: sno00335-bmc-secret
  bootMACAddress: '52:54:00:76:13:0c'
  automatedCleaningMode: disabled
  online: true
