apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00374
  namespace: sno00374
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00374"
  labels:
    infraenvs.agent-install.openshift.io: "sno00374"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/ec2cefcd-4828-4640-8fba-66c188411cba'
    disableCertificateVerification: true
    credentialsName: sno00374-bmc-secret
  bootMACAddress: '52:54:00:76:15:11'
  automatedCleaningMode: disabled
  online: true
