apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00328
  namespace: sno00328
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00328"
  labels:
    infraenvs.agent-install.openshift.io: "sno00328"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/77e2fc65-9cfb-4d07-8025-216684f6486e'
    disableCertificateVerification: true
    credentialsName: sno00328-bmc-secret
  bootMACAddress: '52:54:00:76:13:05'
  automatedCleaningMode: disabled
  online: true
