apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00379
  namespace: sno00379
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00379"
  labels:
    infraenvs.agent-install.openshift.io: "sno00379"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/f4863ea4-0a9b-4525-9803-22bdb40ba09b'
    disableCertificateVerification: true
    credentialsName: sno00379-bmc-secret
  bootMACAddress: '52:54:00:76:16:05'
  automatedCleaningMode: disabled
  online: true
