apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00303
  namespace: sno00303
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00303"
  labels:
    infraenvs.agent-install.openshift.io: "sno00303"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/dcda444e-d211-4f1d-921f-e4b76ea99d8a'
    disableCertificateVerification: true
    credentialsName: sno00303-bmc-secret
  bootMACAddress: '52:54:00:76:11:0e'
  automatedCleaningMode: disabled
  online: true
