apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00339
  namespace: sno00339
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00339"
  labels:
    infraenvs.agent-install.openshift.io: "sno00339"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/763d11e7-4ce6-4cf4-b127-2ebd9748fb97'
    disableCertificateVerification: true
    credentialsName: sno00339-bmc-secret
  bootMACAddress: '52:54:00:76:13:10'
  automatedCleaningMode: disabled
  online: true
