apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00369
  namespace: sno00369
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00369"
  labels:
    infraenvs.agent-install.openshift.io: "sno00369"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/326e7fd4-6555-4c10-aba4-a59f277b13f2'
    disableCertificateVerification: true
    credentialsName: sno00369-bmc-secret
  bootMACAddress: '52:54:00:76:15:0c'
  automatedCleaningMode: disabled
  online: true
