apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00388
  namespace: sno00388
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00388"
  labels:
    infraenvs.agent-install.openshift.io: "sno00388"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/cb29cd08-70dc-479d-91d3-de5e2ec89ccf'
    disableCertificateVerification: true
    credentialsName: sno00388-bmc-secret
  bootMACAddress: '52:54:00:76:16:0e'
  automatedCleaningMode: disabled
  online: true
