apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00312
  namespace: sno00312
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00312"
  labels:
    infraenvs.agent-install.openshift.io: "sno00312"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/7927ab00-384e-45a2-8c96-b01c32075128'
    disableCertificateVerification: true
    credentialsName: sno00312-bmc-secret
  bootMACAddress: '52:54:00:76:12:06'
  automatedCleaningMode: disabled
  online: true
