apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00366
  namespace: sno00366
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00366"
  labels:
    infraenvs.agent-install.openshift.io: "sno00366"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/bc264390-11c7-49a4-9c89-c70474aabae7'
    disableCertificateVerification: true
    credentialsName: sno00366-bmc-secret
  bootMACAddress: '52:54:00:76:15:09'
  automatedCleaningMode: disabled
  online: true
