apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00353
  namespace: sno00353
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00353"
  labels:
    infraenvs.agent-install.openshift.io: "sno00353"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/4899b94a-82f9-4a3b-88d3-ea74b73781af'
    disableCertificateVerification: true
    credentialsName: sno00353-bmc-secret
  bootMACAddress: '52:54:00:76:14:0d'
  automatedCleaningMode: disabled
  online: true
