apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00317
  namespace: sno00317
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00317"
  labels:
    infraenvs.agent-install.openshift.io: "sno00317"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/4152e428-e49e-4044-9ae8-aa7f91a9ac71'
    disableCertificateVerification: true
    credentialsName: sno00317-bmc-secret
  bootMACAddress: '52:54:00:76:12:0b'
  automatedCleaningMode: disabled
  online: true
