apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00336
  namespace: sno00336
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00336"
  labels:
    infraenvs.agent-install.openshift.io: "sno00336"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/25cf4a7e-72e1-4762-b3fa-11db8cbbead1'
    disableCertificateVerification: true
    credentialsName: sno00336-bmc-secret
  bootMACAddress: '52:54:00:76:13:0d'
  automatedCleaningMode: disabled
  online: true
