apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00309
  namespace: sno00309
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00309"
  labels:
    infraenvs.agent-install.openshift.io: "sno00309"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/f39111a7-9e17-4e4c-b9a7-b09c35ca6917'
    disableCertificateVerification: true
    credentialsName: sno00309-bmc-secret
  bootMACAddress: '52:54:00:76:12:03'
  automatedCleaningMode: disabled
  online: true
