apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00389
  namespace: sno00389
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00389"
  labels:
    infraenvs.agent-install.openshift.io: "sno00389"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/2526365d-baac-49d1-98c6-d5b893f7bc54'
    disableCertificateVerification: true
    credentialsName: sno00389-bmc-secret
  bootMACAddress: '52:54:00:76:16:0f'
  automatedCleaningMode: disabled
  online: true
