apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00313
  namespace: sno00313
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00313"
  labels:
    infraenvs.agent-install.openshift.io: "sno00313"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/f99be929-cd07-413b-ae53-76a3efe75976'
    disableCertificateVerification: true
    credentialsName: sno00313-bmc-secret
  bootMACAddress: '52:54:00:76:12:07'
  automatedCleaningMode: disabled
  online: true
