apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00368
  namespace: sno00368
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00368"
  labels:
    infraenvs.agent-install.openshift.io: "sno00368"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/96fc3987-9ba2-4ca4-a543-e821b28e257c'
    disableCertificateVerification: true
    credentialsName: sno00368-bmc-secret
  bootMACAddress: '52:54:00:76:15:0b'
  automatedCleaningMode: disabled
  online: true
