apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00370
  namespace: sno00370
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00370"
  labels:
    infraenvs.agent-install.openshift.io: "sno00370"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/df0ac078-eb5c-4140-89a2-47c38b8bcbbd'
    disableCertificateVerification: true
    credentialsName: sno00370-bmc-secret
  bootMACAddress: '52:54:00:76:15:0d'
  automatedCleaningMode: disabled
  online: true
