apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00378
  namespace: sno00378
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00378"
  labels:
    infraenvs.agent-install.openshift.io: "sno00378"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/b9c9e1fb-997d-4e48-aff8-44b71b8d6cfb'
    disableCertificateVerification: true
    credentialsName: sno00378-bmc-secret
  bootMACAddress: '52:54:00:76:16:04'
  automatedCleaningMode: disabled
  online: true
