apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00311
  namespace: sno00311
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00311"
  labels:
    infraenvs.agent-install.openshift.io: "sno00311"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/b2c586f1-3399-4b25-90ff-d97b593836fd'
    disableCertificateVerification: true
    credentialsName: sno00311-bmc-secret
  bootMACAddress: '52:54:00:76:12:05'
  automatedCleaningMode: disabled
  online: true
