apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00354
  namespace: sno00354
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00354"
  labels:
    infraenvs.agent-install.openshift.io: "sno00354"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/3901c5e5-ab93-4217-93e0-afc3990ab86d'
    disableCertificateVerification: true
    credentialsName: sno00354-bmc-secret
  bootMACAddress: '52:54:00:76:14:0e'
  automatedCleaningMode: disabled
  online: true
