apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00345
  namespace: sno00345
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00345"
  labels:
    infraenvs.agent-install.openshift.io: "sno00345"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/07edd172-5e57-4e2b-9043-b4e13780bc8f'
    disableCertificateVerification: true
    credentialsName: sno00345-bmc-secret
  bootMACAddress: '52:54:00:76:14:05'
  automatedCleaningMode: disabled
  online: true
