apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00325
  namespace: sno00325
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00325"
  labels:
    infraenvs.agent-install.openshift.io: "sno00325"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/eef464f6-f3dd-4436-8ea2-6e239315d1a8'
    disableCertificateVerification: true
    credentialsName: sno00325-bmc-secret
  bootMACAddress: '52:54:00:76:13:02'
  automatedCleaningMode: disabled
  online: true
