apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00359
  namespace: sno00359
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00359"
  labels:
    infraenvs.agent-install.openshift.io: "sno00359"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.39:9000/redfish/v1/Systems/74699311-4ff5-4c29-bb04-e0899cda362d'
    disableCertificateVerification: true
    credentialsName: sno00359-bmc-secret
  bootMACAddress: '52:54:00:76:15:02'
  automatedCleaningMode: disabled
  online: true
