apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00327
  namespace: sno00327
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00327"
  labels:
    infraenvs.agent-install.openshift.io: "sno00327"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/9188781b-6453-4ffb-a988-2d3d49adde13'
    disableCertificateVerification: true
    credentialsName: sno00327-bmc-secret
  bootMACAddress: '52:54:00:76:13:04'
  automatedCleaningMode: disabled
  online: true
