apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00308
  namespace: sno00308
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00308"
  labels:
    infraenvs.agent-install.openshift.io: "sno00308"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/3b2ac4d5-0bb1-4181-8e88-82b5f0a35662'
    disableCertificateVerification: true
    credentialsName: sno00308-bmc-secret
  bootMACAddress: '52:54:00:76:12:02'
  automatedCleaningMode: disabled
  online: true
