apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00342
  namespace: sno00342
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00342"
  labels:
    infraenvs.agent-install.openshift.io: "sno00342"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/9f5f1d9b-9734-4339-9d04-ba5779ebe03a'
    disableCertificateVerification: true
    credentialsName: sno00342-bmc-secret
  bootMACAddress: '52:54:00:76:14:02'
  automatedCleaningMode: disabled
  online: true
