apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00330
  namespace: sno00330
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00330"
  labels:
    infraenvs.agent-install.openshift.io: "sno00330"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.37:9000/redfish/v1/Systems/b2e4bb9c-fa5c-4469-ad53-b38cc18a9fbd'
    disableCertificateVerification: true
    credentialsName: sno00330-bmc-secret
  bootMACAddress: '52:54:00:76:13:07'
  automatedCleaningMode: disabled
  online: true
