apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00310
  namespace: sno00310
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00310"
  labels:
    infraenvs.agent-install.openshift.io: "sno00310"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.36:9000/redfish/v1/Systems/c04964d3-c218-415e-8d3d-ad374c1aefd3'
    disableCertificateVerification: true
    credentialsName: sno00310-bmc-secret
  bootMACAddress: '52:54:00:76:12:04'
  automatedCleaningMode: disabled
  online: true
