apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00399
  namespace: sno00399
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00399"
  labels:
    infraenvs.agent-install.openshift.io: "sno00399"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.41:9000/redfish/v1/Systems/6043fcea-3a0a-450e-b923-8bf05262b6a1'
    disableCertificateVerification: true
    credentialsName: sno00399-bmc-secret
  bootMACAddress: '52:54:00:76:17:08'
  automatedCleaningMode: disabled
  online: true
