apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00302
  namespace: sno00302
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00302"
  labels:
    infraenvs.agent-install.openshift.io: "sno00302"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/c969dc68-4b2b-4586-8d8e-659c76f99751'
    disableCertificateVerification: true
    credentialsName: sno00302-bmc-secret
  bootMACAddress: '52:54:00:76:11:0d'
  automatedCleaningMode: disabled
  online: true
