apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00377
  namespace: sno00377
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00377"
  labels:
    infraenvs.agent-install.openshift.io: "sno00377"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.40:9000/redfish/v1/Systems/9f94d7a3-cd8f-4cbb-85f9-357cdd107a1a'
    disableCertificateVerification: true
    credentialsName: sno00377-bmc-secret
  bootMACAddress: '52:54:00:76:16:03'
  automatedCleaningMode: disabled
  online: true
