apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00356
  namespace: sno00356
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00356"
  labels:
    infraenvs.agent-install.openshift.io: "sno00356"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.38:9000/redfish/v1/Systems/89b35ee6-dcc0-491b-b358-eb8b6fad6428'
    disableCertificateVerification: true
    credentialsName: sno00356-bmc-secret
  bootMACAddress: '52:54:00:76:14:10'
  automatedCleaningMode: disabled
  online: true
