apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00304
  namespace: sno00304
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00304"
  labels:
    infraenvs.agent-install.openshift.io: "sno00304"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.35:9000/redfish/v1/Systems/416da347-6601-4c31-9dbd-cc7d0a32a852'
    disableCertificateVerification: true
    credentialsName: sno00304-bmc-secret
  bootMACAddress: '52:54:00:76:11:0f'
  automatedCleaningMode: disabled
  online: true
