apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00136
  namespace: sno00136
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00136"
  labels:
    infraenvs.agent-install.openshift.io: "sno00136"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/c10ec0a0-d2e7-4f95-afbc-c20a7c0537da'
    disableCertificateVerification: true
    credentialsName: sno00136-bmc-secret
  bootMACAddress: '52:54:00:76:07:11'
  automatedCleaningMode: disabled
  online: true
