apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00169
  namespace: sno00169
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00169"
  labels:
    infraenvs.agent-install.openshift.io: "sno00169"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.27:9000/redfish/v1/Systems/44c864ba-e907-410c-8086-939d8efd60b2'
    disableCertificateVerification: true
    credentialsName: sno00169-bmc-secret
  bootMACAddress: '52:54:00:76:09:10'
  automatedCleaningMode: disabled
  online: true
