apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00192
  namespace: sno00192
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00192"
  labels:
    infraenvs.agent-install.openshift.io: "sno00192"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/0a3ef93e-705d-494f-a50b-b07673c782d2'
    disableCertificateVerification: true
    credentialsName: sno00192-bmc-secret
  bootMACAddress: '52:54:00:76:0b:05'
  automatedCleaningMode: disabled
  online: true
