apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00194
  namespace: sno00194
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00194"
  labels:
    infraenvs.agent-install.openshift.io: "sno00194"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/134935bf-e568-455b-830f-91fed363c845'
    disableCertificateVerification: true
    credentialsName: sno00194-bmc-secret
  bootMACAddress: '52:54:00:76:0b:07'
  automatedCleaningMode: disabled
  online: true
