apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00170
  namespace: sno00170
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00170"
  labels:
    infraenvs.agent-install.openshift.io: "sno00170"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.27:9000/redfish/v1/Systems/eea0eff5-682f-4d37-82d4-fddca0328f86'
    disableCertificateVerification: true
    credentialsName: sno00170-bmc-secret
  bootMACAddress: '52:54:00:76:09:11'
  automatedCleaningMode: disabled
  online: true
