apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00160
  namespace: sno00160
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00160"
  labels:
    infraenvs.agent-install.openshift.io: "sno00160"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.27:9000/redfish/v1/Systems/bd5e55ba-e6f1-40bd-a37d-1b5dbc89df82'
    disableCertificateVerification: true
    credentialsName: sno00160-bmc-secret
  bootMACAddress: '52:54:00:76:09:07'
  automatedCleaningMode: disabled
  online: true
