apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00133
  namespace: sno00133
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00133"
  labels:
    infraenvs.agent-install.openshift.io: "sno00133"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/be4ddb8d-ad70-45da-85ae-2eae65735e11'
    disableCertificateVerification: true
    credentialsName: sno00133-bmc-secret
  bootMACAddress: '52:54:00:76:07:0e'
  automatedCleaningMode: disabled
  online: true
