apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00199
  namespace: sno00199
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00199"
  labels:
    infraenvs.agent-install.openshift.io: "sno00199"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/c9871be5-82ec-4001-8436-76dab824b7ef'
    disableCertificateVerification: true
    credentialsName: sno00199-bmc-secret
  bootMACAddress: '52:54:00:76:0b:0c'
  automatedCleaningMode: disabled
  online: true
