apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00152
  namespace: sno00152
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00152"
  labels:
    infraenvs.agent-install.openshift.io: "sno00152"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.26:9000/redfish/v1/Systems/a2b20ded-8a77-4073-84ea-3ccda70ddfef'
    disableCertificateVerification: true
    credentialsName: sno00152-bmc-secret
  bootMACAddress: '52:54:00:76:08:10'
  automatedCleaningMode: disabled
  online: true
