apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00157
  namespace: sno00157
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00157"
  labels:
    infraenvs.agent-install.openshift.io: "sno00157"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.27:9000/redfish/v1/Systems/3ac055c6-30cb-40ca-bd12-fc7e6be6e849'
    disableCertificateVerification: true
    credentialsName: sno00157-bmc-secret
  bootMACAddress: '52:54:00:76:09:04'
  automatedCleaningMode: disabled
  online: true
