apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00187
  namespace: sno00187
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00187"
  labels:
    infraenvs.agent-install.openshift.io: "sno00187"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/8fc6519d-cbca-4463-a93a-be56c4b9680c'
    disableCertificateVerification: true
    credentialsName: sno00187-bmc-secret
  bootMACAddress: '52:54:00:76:0a:11'
  automatedCleaningMode: disabled
  online: true
