apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00127
  namespace: sno00127
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00127"
  labels:
    infraenvs.agent-install.openshift.io: "sno00127"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/fd02ecd4-94e6-4689-b48f-4a8122aebd83'
    disableCertificateVerification: true
    credentialsName: sno00127-bmc-secret
  bootMACAddress: '52:54:00:76:07:08'
  automatedCleaningMode: disabled
  online: true
