apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00126
  namespace: sno00126
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00126"
  labels:
    infraenvs.agent-install.openshift.io: "sno00126"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/f1485ec8-05d6-4491-bb88-b01f59ba1db2'
    disableCertificateVerification: true
    credentialsName: sno00126-bmc-secret
  bootMACAddress: '52:54:00:76:07:07'
  automatedCleaningMode: disabled
  online: true
