apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00195
  namespace: sno00195
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00195"
  labels:
    infraenvs.agent-install.openshift.io: "sno00195"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/c093e091-04bb-4790-b0e8-f93ddeed3589'
    disableCertificateVerification: true
    credentialsName: sno00195-bmc-secret
  bootMACAddress: '52:54:00:76:0b:08'
  automatedCleaningMode: disabled
  online: true
