apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00107
  namespace: sno00107
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00107"
  labels:
    infraenvs.agent-install.openshift.io: "sno00107"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/592c1df7-406a-4347-87ec-9dbc170ea507'
    disableCertificateVerification: true
    credentialsName: sno00107-bmc-secret
  bootMACAddress: '52:54:00:76:06:05'
  automatedCleaningMode: disabled
  online: true
