apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00101
  namespace: sno00101
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00101"
  labels:
    infraenvs.agent-install.openshift.io: "sno00101"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/c9c87559-0d51-490d-9698-ed2b10bd8348'
    disableCertificateVerification: true
    credentialsName: sno00101-bmc-secret
  bootMACAddress: '52:54:00:76:05:10'
  automatedCleaningMode: disabled
  online: true
