apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00178
  namespace: sno00178
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00178"
  labels:
    infraenvs.agent-install.openshift.io: "sno00178"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/eb98091b-c69e-4e3c-a2d6-9a481fffa0e7'
    disableCertificateVerification: true
    credentialsName: sno00178-bmc-secret
  bootMACAddress: '52:54:00:76:0a:08'
  automatedCleaningMode: disabled
  online: true
