apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00180
  namespace: sno00180
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00180"
  labels:
    infraenvs.agent-install.openshift.io: "sno00180"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/5f86aed5-7ad4-4352-9ad2-611c6e067e29'
    disableCertificateVerification: true
    credentialsName: sno00180-bmc-secret
  bootMACAddress: '52:54:00:76:0a:0a'
  automatedCleaningMode: disabled
  online: true
