apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00176
  namespace: sno00176
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00176"
  labels:
    infraenvs.agent-install.openshift.io: "sno00176"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/7219153f-f59f-44c8-867f-d6dca23efca3'
    disableCertificateVerification: true
    credentialsName: sno00176-bmc-secret
  bootMACAddress: '52:54:00:76:0a:06'
  automatedCleaningMode: disabled
  online: true
