apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00111
  namespace: sno00111
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00111"
  labels:
    infraenvs.agent-install.openshift.io: "sno00111"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/c7607b4a-c419-4cab-be33-3c17c6f11b85'
    disableCertificateVerification: true
    credentialsName: sno00111-bmc-secret
  bootMACAddress: '52:54:00:76:06:09'
  automatedCleaningMode: disabled
  online: true
