apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00119
  namespace: sno00119
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00119"
  labels:
    infraenvs.agent-install.openshift.io: "sno00119"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/ada162d0-db95-4dd4-867e-539c71726064'
    disableCertificateVerification: true
    credentialsName: sno00119-bmc-secret
  bootMACAddress: '52:54:00:76:06:11'
  automatedCleaningMode: disabled
  online: true
