apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00134
  namespace: sno00134
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00134"
  labels:
    infraenvs.agent-install.openshift.io: "sno00134"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/3623f042-65c7-41a0-b51a-33bf815b0a52'
    disableCertificateVerification: true
    credentialsName: sno00134-bmc-secret
  bootMACAddress: '52:54:00:76:07:0f'
  automatedCleaningMode: disabled
  online: true
