apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00102
  namespace: sno00102
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00102"
  labels:
    infraenvs.agent-install.openshift.io: "sno00102"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/b6a1a7a7-3f4f-4a4c-b0ec-c43ba12fefad'
    disableCertificateVerification: true
    credentialsName: sno00102-bmc-secret
  bootMACAddress: '52:54:00:76:05:11'
  automatedCleaningMode: disabled
  online: true
