apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00122
  namespace: sno00122
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00122"
  labels:
    infraenvs.agent-install.openshift.io: "sno00122"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/ff329511-75f2-4120-8fdf-e4736846f25c'
    disableCertificateVerification: true
    credentialsName: sno00122-bmc-secret
  bootMACAddress: '52:54:00:76:07:03'
  automatedCleaningMode: disabled
  online: true
