apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00118
  namespace: sno00118
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00118"
  labels:
    infraenvs.agent-install.openshift.io: "sno00118"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/82a19838-adc8-44e7-ad0b-a2d8d940edce'
    disableCertificateVerification: true
    credentialsName: sno00118-bmc-secret
  bootMACAddress: '52:54:00:76:06:10'
  automatedCleaningMode: disabled
  online: true
