apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00106
  namespace: sno00106
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00106"
  labels:
    infraenvs.agent-install.openshift.io: "sno00106"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/dd2f864d-136e-4185-83db-e3e1280def9e'
    disableCertificateVerification: true
    credentialsName: sno00106-bmc-secret
  bootMACAddress: '52:54:00:76:06:04'
  automatedCleaningMode: disabled
  online: true
