apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00123
  namespace: sno00123
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00123"
  labels:
    infraenvs.agent-install.openshift.io: "sno00123"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/4f7e8967-2dae-4719-ae8a-f7ad32642788'
    disableCertificateVerification: true
    credentialsName: sno00123-bmc-secret
  bootMACAddress: '52:54:00:76:07:04'
  automatedCleaningMode: disabled
  online: true
