apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00174
  namespace: sno00174
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00174"
  labels:
    infraenvs.agent-install.openshift.io: "sno00174"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/8e6ab174-549e-41aa-acb3-9bd996864564'
    disableCertificateVerification: true
    credentialsName: sno00174-bmc-secret
  bootMACAddress: '52:54:00:76:0a:04'
  automatedCleaningMode: disabled
  online: true
