apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00103
  namespace: sno00103
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00103"
  labels:
    infraenvs.agent-install.openshift.io: "sno00103"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/f3e4e763-0007-4e7e-af1a-ba54cce21176'
    disableCertificateVerification: true
    credentialsName: sno00103-bmc-secret
  bootMACAddress: '52:54:00:76:06:01'
  automatedCleaningMode: disabled
  online: true
