apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00104
  namespace: sno00104
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00104"
  labels:
    infraenvs.agent-install.openshift.io: "sno00104"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/b0fdcb61-5597-4149-8f70-ec8e624da837'
    disableCertificateVerification: true
    credentialsName: sno00104-bmc-secret
  bootMACAddress: '52:54:00:76:06:02'
  automatedCleaningMode: disabled
  online: true
