apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00110
  namespace: sno00110
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00110"
  labels:
    infraenvs.agent-install.openshift.io: "sno00110"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/087df58e-54b7-4fb9-9add-6678ae6c285e'
    disableCertificateVerification: true
    credentialsName: sno00110-bmc-secret
  bootMACAddress: '52:54:00:76:06:08'
  automatedCleaningMode: disabled
  online: true
