apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00164
  namespace: sno00164
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00164"
  labels:
    infraenvs.agent-install.openshift.io: "sno00164"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.27:9000/redfish/v1/Systems/52d8e86d-e72c-466e-991b-b443196ec749'
    disableCertificateVerification: true
    credentialsName: sno00164-bmc-secret
  bootMACAddress: '52:54:00:76:09:0b'
  automatedCleaningMode: disabled
  online: true
