apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00191
  namespace: sno00191
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00191"
  labels:
    infraenvs.agent-install.openshift.io: "sno00191"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.29:9000/redfish/v1/Systems/f8435a75-ec29-4c10-a8a8-3919f27969cf'
    disableCertificateVerification: true
    credentialsName: sno00191-bmc-secret
  bootMACAddress: '52:54:00:76:0b:04'
  automatedCleaningMode: disabled
  online: true
