apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00105
  namespace: sno00105
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00105"
  labels:
    infraenvs.agent-install.openshift.io: "sno00105"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/dadaa55c-51f3-434c-a196-438a9ea4dbc5'
    disableCertificateVerification: true
    credentialsName: sno00105-bmc-secret
  bootMACAddress: '52:54:00:76:06:03'
  automatedCleaningMode: disabled
  online: true
