apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00128
  namespace: sno00128
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00128"
  labels:
    infraenvs.agent-install.openshift.io: "sno00128"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/8564cb36-2708-4f1a-9c84-1d83eddae2d5'
    disableCertificateVerification: true
    credentialsName: sno00128-bmc-secret
  bootMACAddress: '52:54:00:76:07:09'
  automatedCleaningMode: disabled
  online: true
