apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00112
  namespace: sno00112
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00112"
  labels:
    infraenvs.agent-install.openshift.io: "sno00112"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/5eaffb48-c746-4ff0-a892-98de0d16c4b9'
    disableCertificateVerification: true
    credentialsName: sno00112-bmc-secret
  bootMACAddress: '52:54:00:76:06:0a'
  automatedCleaningMode: disabled
  online: true
