apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00132
  namespace: sno00132
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00132"
  labels:
    infraenvs.agent-install.openshift.io: "sno00132"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/b8d2aa19-2669-4482-b03c-076f541688ed'
    disableCertificateVerification: true
    credentialsName: sno00132-bmc-secret
  bootMACAddress: '52:54:00:76:07:0d'
  automatedCleaningMode: disabled
  online: true
