apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00115
  namespace: sno00115
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00115"
  labels:
    infraenvs.agent-install.openshift.io: "sno00115"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/5b74dfbc-6ea5-416e-863b-9393074470ab'
    disableCertificateVerification: true
    credentialsName: sno00115-bmc-secret
  bootMACAddress: '52:54:00:76:06:0d'
  automatedCleaningMode: disabled
  online: true
