apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00158
  namespace: sno00158
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00158"
  labels:
    infraenvs.agent-install.openshift.io: "sno00158"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.27:9000/redfish/v1/Systems/b0a90431-ebd2-40cd-bd04-8cf2040f50aa'
    disableCertificateVerification: true
    credentialsName: sno00158-bmc-secret
  bootMACAddress: '52:54:00:76:09:05'
  automatedCleaningMode: disabled
  online: true
