apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00135
  namespace: sno00135
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00135"
  labels:
    infraenvs.agent-install.openshift.io: "sno00135"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/0a33f683-2d4f-4e29-8ea7-a4d1fc90e45f'
    disableCertificateVerification: true
    credentialsName: sno00135-bmc-secret
  bootMACAddress: '52:54:00:76:07:10'
  automatedCleaningMode: disabled
  online: true
