apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00171
  namespace: sno00171
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00171"
  labels:
    infraenvs.agent-install.openshift.io: "sno00171"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/5c1bd049-71f9-4183-8bd6-e22055ab2777'
    disableCertificateVerification: true
    credentialsName: sno00171-bmc-secret
  bootMACAddress: '52:54:00:76:0a:01'
  automatedCleaningMode: disabled
  online: true
