apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00125
  namespace: sno00125
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00125"
  labels:
    infraenvs.agent-install.openshift.io: "sno00125"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/cec72956-44ad-4908-becc-223660b1e9ba'
    disableCertificateVerification: true
    credentialsName: sno00125-bmc-secret
  bootMACAddress: '52:54:00:76:07:06'
  automatedCleaningMode: disabled
  online: true
