apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00121
  namespace: sno00121
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00121"
  labels:
    infraenvs.agent-install.openshift.io: "sno00121"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.25:9000/redfish/v1/Systems/4e8dfcec-6cab-43af-83f9-a1016655559f'
    disableCertificateVerification: true
    credentialsName: sno00121-bmc-secret
  bootMACAddress: '52:54:00:76:07:02'
  automatedCleaningMode: disabled
  online: true
