apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00183
  namespace: sno00183
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00183"
  labels:
    infraenvs.agent-install.openshift.io: "sno00183"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.28:9000/redfish/v1/Systems/8b211920-b0b3-419b-9cd1-c61e17ee6192'
    disableCertificateVerification: true
    credentialsName: sno00183-bmc-secret
  bootMACAddress: '52:54:00:76:0a:0d'
  automatedCleaningMode: disabled
  online: true
