apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00117
  namespace: sno00117
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00117"
  labels:
    infraenvs.agent-install.openshift.io: "sno00117"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.24:9000/redfish/v1/Systems/28f52cef-4d10-4902-8149-c46ffe70a9d4'
    disableCertificateVerification: true
    credentialsName: sno00117-bmc-secret
  bootMACAddress: '52:54:00:76:06:0f'
  automatedCleaningMode: disabled
  online: true
