apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00495
  namespace: sno00495
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00495"
  labels:
    infraenvs.agent-install.openshift.io: "sno00495"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.52:9000/redfish/v1/Systems/e893ebb9-426b-41a9-9f7c-26eba201d118'
    disableCertificateVerification: true
    credentialsName: sno00495-bmc-secret
  bootMACAddress: '52:54:00:76:22:07'
  automatedCleaningMode: disabled
  online: true
