apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00499
  namespace: sno00499
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00499"
  labels:
    infraenvs.agent-install.openshift.io: "sno00499"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.53:9000/redfish/v1/Systems/37bfbb96-6194-403b-8b0a-92b170aed9e1'
    disableCertificateVerification: true
    credentialsName: sno00499-bmc-secret
  bootMACAddress: '52:54:00:76:23:04'
  automatedCleaningMode: disabled
  online: true
