apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00414
  namespace: sno00414
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00414"
  labels:
    infraenvs.agent-install.openshift.io: "sno00414"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.42:9000/redfish/v1/Systems/1b27d479-419b-44d1-b879-0348bf66210c'
    disableCertificateVerification: true
    credentialsName: sno00414-bmc-secret
  bootMACAddress: '52:54:00:76:18:06'
  automatedCleaningMode: disabled
  online: true
