apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00496
  namespace: sno00496
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00496"
  labels:
    infraenvs.agent-install.openshift.io: "sno00496"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.53:9000/redfish/v1/Systems/7a48de06-938c-49f7-bb8f-4942c9b17b54'
    disableCertificateVerification: true
    credentialsName: sno00496-bmc-secret
  bootMACAddress: '52:54:00:76:23:01'
  automatedCleaningMode: disabled
  online: true
