apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00410
  namespace: sno00410
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00410"
  labels:
    infraenvs.agent-install.openshift.io: "sno00410"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.42:9000/redfish/v1/Systems/e7af4a06-40fb-4a01-8cad-6cb3a7221b31'
    disableCertificateVerification: true
    credentialsName: sno00410-bmc-secret
  bootMACAddress: '52:54:00:76:18:02'
  automatedCleaningMode: disabled
  online: true
