apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00411
  namespace: sno00411
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00411"
  labels:
    infraenvs.agent-install.openshift.io: "sno00411"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.42:9000/redfish/v1/Systems/ab35df24-66ca-41fa-8026-d7b26f2085c3'
    disableCertificateVerification: true
    credentialsName: sno00411-bmc-secret
  bootMACAddress: '52:54:00:76:18:03'
  automatedCleaningMode: disabled
  online: true
