apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00444
  namespace: sno00444
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00444"
  labels:
    infraenvs.agent-install.openshift.io: "sno00444"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.45:9000/redfish/v1/Systems/3ef85bc6-b578-4593-9a85-471e97d7b1c6'
    disableCertificateVerification: true
    credentialsName: sno00444-bmc-secret
  bootMACAddress: '52:54:00:76:1b:05'
  automatedCleaningMode: disabled
  online: true
