apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00460
  namespace: sno00460
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00460"
  labels:
    infraenvs.agent-install.openshift.io: "sno00460"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.47:9000/redfish/v1/Systems/1b62af70-f7c5-47e5-b093-34de085575db'
    disableCertificateVerification: true
    credentialsName: sno00460-bmc-secret
  bootMACAddress: '52:54:00:76:1d:07'
  automatedCleaningMode: disabled
  online: true
