apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00407
  namespace: sno00407
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00407"
  labels:
    infraenvs.agent-install.openshift.io: "sno00407"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.41:9000/redfish/v1/Systems/ec69baa1-7b12-4044-b6d9-dacf134f319f'
    disableCertificateVerification: true
    credentialsName: sno00407-bmc-secret
  bootMACAddress: '52:54:00:76:17:10'
  automatedCleaningMode: disabled
  online: true
