apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00480
  namespace: sno00480
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00480"
  labels:
    infraenvs.agent-install.openshift.io: "sno00480"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.50:9000/redfish/v1/Systems/e7d30fc2-123d-4b27-87e9-f700da4fc191'
    disableCertificateVerification: true
    credentialsName: sno00480-bmc-secret
  bootMACAddress: '52:54:00:76:20:06'
  automatedCleaningMode: disabled
  online: true
