apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00400
  namespace: sno00400
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00400"
  labels:
    infraenvs.agent-install.openshift.io: "sno00400"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.41:9000/redfish/v1/Systems/d9dd8c87-530e-4681-be67-39b2600b8e58'
    disableCertificateVerification: true
    credentialsName: sno00400-bmc-secret
  bootMACAddress: '52:54:00:76:17:09'
  automatedCleaningMode: disabled
  online: true
