apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00405
  namespace: sno00405
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00405"
  labels:
    infraenvs.agent-install.openshift.io: "sno00405"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.41:9000/redfish/v1/Systems/4d19d730-1023-405d-b5e4-161e44f62f1f'
    disableCertificateVerification: true
    credentialsName: sno00405-bmc-secret
  bootMACAddress: '52:54:00:76:17:0e'
  automatedCleaningMode: disabled
  online: true
