apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00458
  namespace: sno00458
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00458"
  labels:
    infraenvs.agent-install.openshift.io: "sno00458"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.47:9000/redfish/v1/Systems/c0cfb1d2-62c2-46ca-8fb9-401dcc8f2bdf'
    disableCertificateVerification: true
    credentialsName: sno00458-bmc-secret
  bootMACAddress: '52:54:00:76:1d:05'
  automatedCleaningMode: disabled
  online: true
