apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00424
  namespace: sno00424
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00424"
  labels:
    infraenvs.agent-install.openshift.io: "sno00424"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.42:9000/redfish/v1/Systems/d7d217db-a5ca-4939-ae9c-4517847fa7cc'
    disableCertificateVerification: true
    credentialsName: sno00424-bmc-secret
  bootMACAddress: '52:54:00:76:18:10'
  automatedCleaningMode: disabled
  online: true
