apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00453
  namespace: sno00453
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00453"
  labels:
    infraenvs.agent-install.openshift.io: "sno00453"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.46:9000/redfish/v1/Systems/f0192365-f3d6-4ac1-970f-1e0b3bc9df4b'
    disableCertificateVerification: true
    credentialsName: sno00453-bmc-secret
  bootMACAddress: '52:54:00:76:1c:07'
  automatedCleaningMode: disabled
  online: true
