apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00434
  namespace: sno00434
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00434"
  labels:
    infraenvs.agent-install.openshift.io: "sno00434"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.44:9000/redfish/v1/Systems/127b7865-b634-4412-bd3d-b9d18dc887ad'
    disableCertificateVerification: true
    credentialsName: sno00434-bmc-secret
  bootMACAddress: '52:54:00:76:1a:02'
  automatedCleaningMode: disabled
  online: true
