apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00425
  namespace: sno00425
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00425"
  labels:
    infraenvs.agent-install.openshift.io: "sno00425"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.42:9000/redfish/v1/Systems/f83b1c11-cd8a-474d-9a17-c130106ad916'
    disableCertificateVerification: true
    credentialsName: sno00425-bmc-secret
  bootMACAddress: '52:54:00:76:18:11'
  automatedCleaningMode: disabled
  online: true
