apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00445
  namespace: sno00445
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00445"
  labels:
    infraenvs.agent-install.openshift.io: "sno00445"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.45:9000/redfish/v1/Systems/17f10d72-08ac-4abe-b530-03f40fc6f798'
    disableCertificateVerification: true
    credentialsName: sno00445-bmc-secret
  bootMACAddress: '52:54:00:76:1b:06'
  automatedCleaningMode: disabled
  online: true
