apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00450
  namespace: sno00450
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00450"
  labels:
    infraenvs.agent-install.openshift.io: "sno00450"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.46:9000/redfish/v1/Systems/76905205-d3b0-4ffe-879d-34eb17adca33'
    disableCertificateVerification: true
    credentialsName: sno00450-bmc-secret
  bootMACAddress: '52:54:00:76:1c:04'
  automatedCleaningMode: disabled
  online: true
