apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00431
  namespace: sno00431
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00431"
  labels:
    infraenvs.agent-install.openshift.io: "sno00431"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.43:9000/redfish/v1/Systems/5fcb543f-a990-4737-8392-50e1df27fc33'
    disableCertificateVerification: true
    credentialsName: sno00431-bmc-secret
  bootMACAddress: '52:54:00:76:19:06'
  automatedCleaningMode: disabled
  online: true
