apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00485
  namespace: sno00485
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00485"
  labels:
    infraenvs.agent-install.openshift.io: "sno00485"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.51:9000/redfish/v1/Systems/ea004ee4-f841-4e98-8983-74b46e399ac1'
    disableCertificateVerification: true
    credentialsName: sno00485-bmc-secret
  bootMACAddress: '52:54:00:76:21:04'
  automatedCleaningMode: disabled
  online: true
