apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00469
  namespace: sno00469
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00469"
  labels:
    infraenvs.agent-install.openshift.io: "sno00469"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.49:9000/redfish/v1/Systems/2ea60668-e4d7-449d-af9f-340ddb29ed5a'
    disableCertificateVerification: true
    credentialsName: sno00469-bmc-secret
  bootMACAddress: '52:54:00:76:1f:02'
  automatedCleaningMode: disabled
  online: true
