apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00478
  namespace: sno00478
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00478"
  labels:
    infraenvs.agent-install.openshift.io: "sno00478"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.50:9000/redfish/v1/Systems/9f17affa-b8fc-496a-a151-272cd0551b53'
    disableCertificateVerification: true
    credentialsName: sno00478-bmc-secret
  bootMACAddress: '52:54:00:76:20:04'
  automatedCleaningMode: disabled
  online: true
