apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00470
  namespace: sno00470
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00470"
  labels:
    infraenvs.agent-install.openshift.io: "sno00470"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.49:9000/redfish/v1/Systems/28b4d4f3-38f3-41b3-acc3-0b5ca1acc493'
    disableCertificateVerification: true
    credentialsName: sno00470-bmc-secret
  bootMACAddress: '52:54:00:76:1f:03'
  automatedCleaningMode: disabled
  online: true
