apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00415
  namespace: sno00415
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00415"
  labels:
    infraenvs.agent-install.openshift.io: "sno00415"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.42:9000/redfish/v1/Systems/ec833c90-e184-45bc-a070-b426013474e0'
    disableCertificateVerification: true
    credentialsName: sno00415-bmc-secret
  bootMACAddress: '52:54:00:76:18:07'
  automatedCleaningMode: disabled
  online: true
