apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00463
  namespace: sno00463
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00463"
  labels:
    infraenvs.agent-install.openshift.io: "sno00463"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.48:9000/redfish/v1/Systems/f1d066e4-8ffb-4631-b26a-6b36f4f9275f'
    disableCertificateVerification: true
    credentialsName: sno00463-bmc-secret
  bootMACAddress: '52:54:00:76:1e:03'
  automatedCleaningMode: disabled
  online: true
