apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00473
  namespace: sno00473
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00473"
  labels:
    infraenvs.agent-install.openshift.io: "sno00473"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.49:9000/redfish/v1/Systems/a7d08207-f957-429c-9acd-9add8fa294d0'
    disableCertificateVerification: true
    credentialsName: sno00473-bmc-secret
  bootMACAddress: '52:54:00:76:1f:06'
  automatedCleaningMode: disabled
  online: true
