apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00487
  namespace: sno00487
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00487"
  labels:
    infraenvs.agent-install.openshift.io: "sno00487"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.51:9000/redfish/v1/Systems/809b6230-7496-44c7-b867-0f8bc9d6131b'
    disableCertificateVerification: true
    credentialsName: sno00487-bmc-secret
  bootMACAddress: '52:54:00:76:21:06'
  automatedCleaningMode: disabled
  online: true
