apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00430
  namespace: sno00430
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00430"
  labels:
    infraenvs.agent-install.openshift.io: "sno00430"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.43:9000/redfish/v1/Systems/2785c858-5622-4edf-91e7-d4d0cb1a1328'
    disableCertificateVerification: true
    credentialsName: sno00430-bmc-secret
  bootMACAddress: '52:54:00:76:19:05'
  automatedCleaningMode: disabled
  online: true
