apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00446
  namespace: sno00446
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00446"
  labels:
    infraenvs.agent-install.openshift.io: "sno00446"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.45:9000/redfish/v1/Systems/1f7c713e-cdf2-44f8-8dbd-17c026166a84'
    disableCertificateVerification: true
    credentialsName: sno00446-bmc-secret
  bootMACAddress: '52:54:00:76:1b:07'
  automatedCleaningMode: disabled
  online: true
