apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00455
  namespace: sno00455
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00455"
  labels:
    infraenvs.agent-install.openshift.io: "sno00455"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.47:9000/redfish/v1/Systems/a8119880-ded2-4d55-9067-fdf40ab7faf9'
    disableCertificateVerification: true
    credentialsName: sno00455-bmc-secret
  bootMACAddress: '52:54:00:76:1d:02'
  automatedCleaningMode: disabled
  online: true
