apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00427
  namespace: sno00427
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00427"
  labels:
    infraenvs.agent-install.openshift.io: "sno00427"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.43:9000/redfish/v1/Systems/8917b876-c811-40eb-af74-d4182158ae1e'
    disableCertificateVerification: true
    credentialsName: sno00427-bmc-secret
  bootMACAddress: '52:54:00:76:19:02'
  automatedCleaningMode: disabled
  online: true
