apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00442
  namespace: sno00442
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00442"
  labels:
    infraenvs.agent-install.openshift.io: "sno00442"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.45:9000/redfish/v1/Systems/f01e40e4-8c66-4bea-a7cc-387ac17f6b01'
    disableCertificateVerification: true
    credentialsName: sno00442-bmc-secret
  bootMACAddress: '52:54:00:76:1b:03'
  automatedCleaningMode: disabled
  online: true
