apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00402
  namespace: sno00402
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00402"
  labels:
    infraenvs.agent-install.openshift.io: "sno00402"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.41:9000/redfish/v1/Systems/e1a641f5-57dd-4b5b-bba6-03cd58a2dc1f'
    disableCertificateVerification: true
    credentialsName: sno00402-bmc-secret
  bootMACAddress: '52:54:00:76:17:0b'
  automatedCleaningMode: disabled
  online: true
