apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00481
  namespace: sno00481
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00481"
  labels:
    infraenvs.agent-install.openshift.io: "sno00481"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.50:9000/redfish/v1/Systems/46c085f3-4405-49f9-9b4b-3439c127b34d'
    disableCertificateVerification: true
    credentialsName: sno00481-bmc-secret
  bootMACAddress: '52:54:00:76:20:07'
  automatedCleaningMode: disabled
  online: true
