apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00456
  namespace: sno00456
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00456"
  labels:
    infraenvs.agent-install.openshift.io: "sno00456"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.47:9000/redfish/v1/Systems/831aa4a9-8df0-4ca0-85dd-273131454b36'
    disableCertificateVerification: true
    credentialsName: sno00456-bmc-secret
  bootMACAddress: '52:54:00:76:1d:03'
  automatedCleaningMode: disabled
  online: true
