apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00466
  namespace: sno00466
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00466"
  labels:
    infraenvs.agent-install.openshift.io: "sno00466"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.48:9000/redfish/v1/Systems/6fba76b5-600e-4378-8fcb-0772a0e0951f'
    disableCertificateVerification: true
    credentialsName: sno00466-bmc-secret
  bootMACAddress: '52:54:00:76:1e:06'
  automatedCleaningMode: disabled
  online: true
