apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00429
  namespace: sno00429
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00429"
  labels:
    infraenvs.agent-install.openshift.io: "sno00429"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.43:9000/redfish/v1/Systems/2c80b248-e2d0-4a1c-85c9-82f8e412588e'
    disableCertificateVerification: true
    credentialsName: sno00429-bmc-secret
  bootMACAddress: '52:54:00:76:19:04'
  automatedCleaningMode: disabled
  online: true
