apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00464
  namespace: sno00464
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00464"
  labels:
    infraenvs.agent-install.openshift.io: "sno00464"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.48:9000/redfish/v1/Systems/d0619ea5-0339-4a5c-aeed-9465b6d594e9'
    disableCertificateVerification: true
    credentialsName: sno00464-bmc-secret
  bootMACAddress: '52:54:00:76:1e:04'
  automatedCleaningMode: disabled
  online: true
