apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00498
  namespace: sno00498
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00498"
  labels:
    infraenvs.agent-install.openshift.io: "sno00498"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.53:9000/redfish/v1/Systems/1e1c0ae7-4aa9-4d4c-ba33-b1356605b393'
    disableCertificateVerification: true
    credentialsName: sno00498-bmc-secret
  bootMACAddress: '52:54:00:76:23:03'
  automatedCleaningMode: disabled
  online: true
