apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00403
  namespace: sno00403
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00403"
  labels:
    infraenvs.agent-install.openshift.io: "sno00403"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.41:9000/redfish/v1/Systems/c4bb1eb2-2de9-4be2-adea-8159f5563a1f'
    disableCertificateVerification: true
    credentialsName: sno00403-bmc-secret
  bootMACAddress: '52:54:00:76:17:0c'
  automatedCleaningMode: disabled
  online: true
