apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00437
  namespace: sno00437
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00437"
  labels:
    infraenvs.agent-install.openshift.io: "sno00437"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.44:9000/redfish/v1/Systems/832e96f0-245d-4efa-96c9-4239996b3518'
    disableCertificateVerification: true
    credentialsName: sno00437-bmc-secret
  bootMACAddress: '52:54:00:76:1a:05'
  automatedCleaningMode: disabled
  online: true
