apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00449
  namespace: sno00449
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00449"
  labels:
    infraenvs.agent-install.openshift.io: "sno00449"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.46:9000/redfish/v1/Systems/5534bb75-cc28-4ae1-9e6d-54bfa4f00ae9'
    disableCertificateVerification: true
    credentialsName: sno00449-bmc-secret
  bootMACAddress: '52:54:00:76:1c:03'
  automatedCleaningMode: disabled
  online: true
