apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00015
  namespace: sno00015
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00015"
  labels:
    infraenvs.agent-install.openshift.io: "sno00015"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.18:9000/redfish/v1/Systems/06eb7565-d8d2-4eca-9e55-873dfa69ee44'
    disableCertificateVerification: true
    credentialsName: sno00015-bmc-secret
  bootMACAddress: '52:54:00:76:00:0f'
  automatedCleaningMode: disabled
  online: true
