apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00098
  namespace: sno00098
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00098"
  labels:
    infraenvs.agent-install.openshift.io: "sno00098"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/b5c2c689-8cf3-47dd-b85d-e11cefd0a7b2'
    disableCertificateVerification: true
    credentialsName: sno00098-bmc-secret
  bootMACAddress: '52:54:00:76:05:0d'
  automatedCleaningMode: disabled
  online: true
