apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00035
  namespace: sno00035
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00035"
  labels:
    infraenvs.agent-install.openshift.io: "sno00035"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/1e7b4fcc-4684-4893-84cb-2605914ee95c'
    disableCertificateVerification: true
    credentialsName: sno00035-bmc-secret
  bootMACAddress: '52:54:00:76:02:01'
  automatedCleaningMode: disabled
  online: true
