apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00013
  namespace: sno00013
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00013"
  labels:
    infraenvs.agent-install.openshift.io: "sno00013"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.18:9000/redfish/v1/Systems/9175e022-9240-45f1-80ba-672f065ef8e4'
    disableCertificateVerification: true
    credentialsName: sno00013-bmc-secret
  bootMACAddress: '52:54:00:76:00:0d'
  automatedCleaningMode: disabled
  online: true
