apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00050
  namespace: sno00050
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00050"
  labels:
    infraenvs.agent-install.openshift.io: "sno00050"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/937f1d93-0245-4c09-9ec1-966d52a90d73'
    disableCertificateVerification: true
    credentialsName: sno00050-bmc-secret
  bootMACAddress: '52:54:00:76:02:10'
  automatedCleaningMode: disabled
  online: true
