apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00034
  namespace: sno00034
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00034"
  labels:
    infraenvs.agent-install.openshift.io: "sno00034"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.19:9000/redfish/v1/Systems/e0b00396-d3e8-4162-93c3-6e0c79897788'
    disableCertificateVerification: true
    credentialsName: sno00034-bmc-secret
  bootMACAddress: '52:54:00:76:01:11'
  automatedCleaningMode: disabled
  online: true
