apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00038
  namespace: sno00038
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00038"
  labels:
    infraenvs.agent-install.openshift.io: "sno00038"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/977a9945-c363-4268-beb3-0fcbe5d0ee12'
    disableCertificateVerification: true
    credentialsName: sno00038-bmc-secret
  bootMACAddress: '52:54:00:76:02:04'
  automatedCleaningMode: disabled
  online: true
