apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00053
  namespace: sno00053
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00053"
  labels:
    infraenvs.agent-install.openshift.io: "sno00053"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.21:9000/redfish/v1/Systems/7235561b-088f-4253-9222-4038d3ae326a'
    disableCertificateVerification: true
    credentialsName: sno00053-bmc-secret
  bootMACAddress: '52:54:00:76:03:02'
  automatedCleaningMode: disabled
  online: true
