apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00043
  namespace: sno00043
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00043"
  labels:
    infraenvs.agent-install.openshift.io: "sno00043"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/8a640a1b-b965-4528-8bb6-e9b777dbfb28'
    disableCertificateVerification: true
    credentialsName: sno00043-bmc-secret
  bootMACAddress: '52:54:00:76:02:09'
  automatedCleaningMode: disabled
  online: true
