apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00026
  namespace: sno00026
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00026"
  labels:
    infraenvs.agent-install.openshift.io: "sno00026"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.19:9000/redfish/v1/Systems/66b49c52-31ff-42b3-b02c-962543631c66'
    disableCertificateVerification: true
    credentialsName: sno00026-bmc-secret
  bootMACAddress: '52:54:00:76:01:09'
  automatedCleaningMode: disabled
  online: true
