apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00056
  namespace: sno00056
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00056"
  labels:
    infraenvs.agent-install.openshift.io: "sno00056"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.21:9000/redfish/v1/Systems/ba238f63-a7c7-4f4d-a6a5-2746ba91fcb0'
    disableCertificateVerification: true
    credentialsName: sno00056-bmc-secret
  bootMACAddress: '52:54:00:76:03:05'
  automatedCleaningMode: disabled
  online: true
