apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00099
  namespace: sno00099
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00099"
  labels:
    infraenvs.agent-install.openshift.io: "sno00099"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/55977354-5af3-4d03-b187-ac4d8821367a'
    disableCertificateVerification: true
    credentialsName: sno00099-bmc-secret
  bootMACAddress: '52:54:00:76:05:0e'
  automatedCleaningMode: disabled
  online: true
