apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00070
  namespace: sno00070
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00070"
  labels:
    infraenvs.agent-install.openshift.io: "sno00070"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/02c0c2e0-aac6-4d6e-b440-505938510de0'
    disableCertificateVerification: true
    credentialsName: sno00070-bmc-secret
  bootMACAddress: '52:54:00:76:04:02'
  automatedCleaningMode: disabled
  online: true
