apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00002
  namespace: sno00002
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00002"
  labels:
    infraenvs.agent-install.openshift.io: "sno00002"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.18:9000/redfish/v1/Systems/a42147a6-eba2-4d87-af75-8175044bd655'
    disableCertificateVerification: true
    credentialsName: sno00002-bmc-secret
  bootMACAddress: '52:54:00:76:00:02'
  automatedCleaningMode: disabled
  online: true
