apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00047
  namespace: sno00047
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00047"
  labels:
    infraenvs.agent-install.openshift.io: "sno00047"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/3b7b31dd-67bf-4f87-801e-0b66b0082235'
    disableCertificateVerification: true
    credentialsName: sno00047-bmc-secret
  bootMACAddress: '52:54:00:76:02:0d'
  automatedCleaningMode: disabled
  online: true
