apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00055
  namespace: sno00055
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00055"
  labels:
    infraenvs.agent-install.openshift.io: "sno00055"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.21:9000/redfish/v1/Systems/7c874397-6d66-453e-8f4b-bb4e020f4f15'
    disableCertificateVerification: true
    credentialsName: sno00055-bmc-secret
  bootMACAddress: '52:54:00:76:03:04'
  automatedCleaningMode: disabled
  online: true
