apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00033
  namespace: sno00033
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00033"
  labels:
    infraenvs.agent-install.openshift.io: "sno00033"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.19:9000/redfish/v1/Systems/3860502a-3674-430f-aa56-db7b446a1eb4'
    disableCertificateVerification: true
    credentialsName: sno00033-bmc-secret
  bootMACAddress: '52:54:00:76:01:10'
  automatedCleaningMode: disabled
  online: true
