apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00079
  namespace: sno00079
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00079"
  labels:
    infraenvs.agent-install.openshift.io: "sno00079"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/28a131de-0c8d-4afc-b4d0-ad640c002d49'
    disableCertificateVerification: true
    credentialsName: sno00079-bmc-secret
  bootMACAddress: '52:54:00:76:04:0b'
  automatedCleaningMode: disabled
  online: true
