apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00041
  namespace: sno00041
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00041"
  labels:
    infraenvs.agent-install.openshift.io: "sno00041"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/ddec0c2a-f9bf-42c3-9d38-305c587be339'
    disableCertificateVerification: true
    credentialsName: sno00041-bmc-secret
  bootMACAddress: '52:54:00:76:02:07'
  automatedCleaningMode: disabled
  online: true
