apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00048
  namespace: sno00048
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00048"
  labels:
    infraenvs.agent-install.openshift.io: "sno00048"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/17577303-2b45-481c-87b5-a8b417794e5c'
    disableCertificateVerification: true
    credentialsName: sno00048-bmc-secret
  bootMACAddress: '52:54:00:76:02:0e'
  automatedCleaningMode: disabled
  online: true
