apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00086
  namespace: sno00086
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00086"
  labels:
    infraenvs.agent-install.openshift.io: "sno00086"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/7cdfce33-bb80-4b5f-90e1-da6c27aa8c1e'
    disableCertificateVerification: true
    credentialsName: sno00086-bmc-secret
  bootMACAddress: '52:54:00:76:05:01'
  automatedCleaningMode: disabled
  online: true
