apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00009
  namespace: sno00009
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00009"
  labels:
    infraenvs.agent-install.openshift.io: "sno00009"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.18:9000/redfish/v1/Systems/077febe0-04bf-4c20-a94a-2e2c1b3f5713'
    disableCertificateVerification: true
    credentialsName: sno00009-bmc-secret
  bootMACAddress: '52:54:00:76:00:09'
  automatedCleaningMode: disabled
  online: true
