apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00062
  namespace: sno00062
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00062"
  labels:
    infraenvs.agent-install.openshift.io: "sno00062"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.21:9000/redfish/v1/Systems/8e9d6e6d-7b98-4648-aec6-0547f6c5c3ff'
    disableCertificateVerification: true
    credentialsName: sno00062-bmc-secret
  bootMACAddress: '52:54:00:76:03:0b'
  automatedCleaningMode: disabled
  online: true
