apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00090
  namespace: sno00090
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00090"
  labels:
    infraenvs.agent-install.openshift.io: "sno00090"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/dac360d4-a01d-4a66-aaaf-d9b7d3ed76f3'
    disableCertificateVerification: true
    credentialsName: sno00090-bmc-secret
  bootMACAddress: '52:54:00:76:05:05'
  automatedCleaningMode: disabled
  online: true
