apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00072
  namespace: sno00072
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00072"
  labels:
    infraenvs.agent-install.openshift.io: "sno00072"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/17438d7b-fc20-4a21-8d6d-bb28a0f6060d'
    disableCertificateVerification: true
    credentialsName: sno00072-bmc-secret
  bootMACAddress: '52:54:00:76:04:04'
  automatedCleaningMode: disabled
  online: true
