apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00077
  namespace: sno00077
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00077"
  labels:
    infraenvs.agent-install.openshift.io: "sno00077"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/4705af44-7716-436a-bff1-3c2785966b2c'
    disableCertificateVerification: true
    credentialsName: sno00077-bmc-secret
  bootMACAddress: '52:54:00:76:04:09'
  automatedCleaningMode: disabled
  online: true
