apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00087
  namespace: sno00087
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00087"
  labels:
    infraenvs.agent-install.openshift.io: "sno00087"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.23:9000/redfish/v1/Systems/f2ac409d-9537-4fc1-b8e2-2dd19536d702'
    disableCertificateVerification: true
    credentialsName: sno00087-bmc-secret
  bootMACAddress: '52:54:00:76:05:02'
  automatedCleaningMode: disabled
  online: true
