apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00054
  namespace: sno00054
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00054"
  labels:
    infraenvs.agent-install.openshift.io: "sno00054"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.21:9000/redfish/v1/Systems/26be3256-e50d-470f-b0dc-a3b22a714975'
    disableCertificateVerification: true
    credentialsName: sno00054-bmc-secret
  bootMACAddress: '52:54:00:76:03:03'
  automatedCleaningMode: disabled
  online: true
