apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00073
  namespace: sno00073
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00073"
  labels:
    infraenvs.agent-install.openshift.io: "sno00073"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/90dd0506-9470-4395-8ee1-70c3e0c4389c'
    disableCertificateVerification: true
    credentialsName: sno00073-bmc-secret
  bootMACAddress: '52:54:00:76:04:05'
  automatedCleaningMode: disabled
  online: true
