apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00011
  namespace: sno00011
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00011"
  labels:
    infraenvs.agent-install.openshift.io: "sno00011"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.18:9000/redfish/v1/Systems/04928e40-645c-4682-97cc-432de4bfaec9'
    disableCertificateVerification: true
    credentialsName: sno00011-bmc-secret
  bootMACAddress: '52:54:00:76:00:0b'
  automatedCleaningMode: disabled
  online: true
