apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00060
  namespace: sno00060
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00060"
  labels:
    infraenvs.agent-install.openshift.io: "sno00060"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.21:9000/redfish/v1/Systems/8bf004df-6929-42ee-94ae-b44569538f68'
    disableCertificateVerification: true
    credentialsName: sno00060-bmc-secret
  bootMACAddress: '52:54:00:76:03:09'
  automatedCleaningMode: disabled
  online: true
