apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00005
  namespace: sno00005
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00005"
  labels:
    infraenvs.agent-install.openshift.io: "sno00005"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.18:9000/redfish/v1/Systems/b7206940-a752-4889-9d3b-0f5ff536be5e'
    disableCertificateVerification: true
    credentialsName: sno00005-bmc-secret
  bootMACAddress: '52:54:00:76:00:05'
  automatedCleaningMode: disabled
  online: true
