apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00049
  namespace: sno00049
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00049"
  labels:
    infraenvs.agent-install.openshift.io: "sno00049"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.20:9000/redfish/v1/Systems/7e6c0e7d-f0d4-4051-8d6d-7e0fdbb7639b'
    disableCertificateVerification: true
    credentialsName: sno00049-bmc-secret
  bootMACAddress: '52:54:00:76:02:0f'
  automatedCleaningMode: disabled
  online: true
