apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00085
  namespace: sno00085
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00085"
  labels:
    infraenvs.agent-install.openshift.io: "sno00085"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/8fe75c22-7c00-4efb-9902-c96144d9491b'
    disableCertificateVerification: true
    credentialsName: sno00085-bmc-secret
  bootMACAddress: '52:54:00:76:04:11'
  automatedCleaningMode: disabled
  online: true
