apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno00080
  namespace: sno00080
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno00080"
  labels:
    infraenvs.agent-install.openshift.io: "sno00080"
spec:
  bootMode: "UEFI"
  bmc:
    address: 'redfish-virtualmedia+http://198.18.8.22:9000/redfish/v1/Systems/8d7ffc32-1049-4f5c-babc-cad0786c52ac'
    disableCertificateVerification: true
    credentialsName: sno00080-bmc-secret
  bootMACAddress: '52:54:00:76:04:0c'
  automatedCleaningMode: disabled
  online: true
